### ISSUE TITLE
Convert byte[] to byte[] or char[] to char[]

### ISSUE THREAD

**Issue by jmarginier** [xebia-france/selma#133]
When i use mapper to convert this class :

```
public class SecureKeyStore {
...
    private byte[] keyStore;
...
    public byte[] getKeyStore() {
        return keyStore;
    }

    public void setKeyStore(byte[] keyStore) {
        this.keyStore = keyStore;
    }
}

```
to : 
```
public class SecureKeyStoreDTO {

    public byte[] keyStore;
.....
    public byte[] getKeyStore() {
        return keyStore;
    }

    public void setKeyStore(byte[] keyStore) {
        this.keyStore = keyStore;
    }
}
```

with this mapper : 
```
@Mapper(withIgnoreMissing = IgnoreMissing.ALL)
public interface SecureKeyStoreMapper {
    SecureKeyStoreDTO asDTO(SecureKeyStore source);

    SecureKeyStore as(SecureKeyStoreDTO in, SecureKeyStore out);
}

```

The generated mapper is : 
System.arraycopy(in.getKeyStore(), 0, **out.setKeyStore**, 0, in.getKeyStore().length);

So he can't work ! It's the same with char[]

Thx

**Comment by slemesle** [comment]
This is fixed in snapshot build

**Comment by jmarginier** [comment]
0.16-SNAPSHOT doesn't fix this error...or I miss something :)

**Comment by slemesle** [comment]
yes, you miss the push :)
