### ISSUE TITLE
NullPointerException if mapper interface has Generic types

### ISSUE THREAD

**Issue by scienty** [xebia-france/selma#63]
```java
@Mapper
public interface IMapper<A, B> {
  public B atob(B bobj);
}
```
I found this issues on 0.12 version with gradle but I think it is related to the build tool.

Caused by: java.lang.NullPointerException
	at fr.xebia.extras.selma.codegen.AnnotationWrapper.buildFor(AnnotationWrapper.java:56)
	at fr.xebia.extras.selma.codegen.MapperWrapper.<init>(MapperWrapper.java:65)
	at fr.xebia.extras.selma.codegen.MapperClassGenerator.<init>(MapperClassGenerator.java:56)
	at fr.xebia.extras.selma.codegen.MapperProcessor.generateMappingClassses(MapperProcessor.java:87)
	at fr.xebia.extras.selma.codegen.MapperProcessor.process(MapperProcessor.java:73)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)

**Comment by scienty** [comment]
There is another case where super interface has Generic type and child interface has @Mapper, compilation fails too

e.g

public interface IMapper<A, B> {
public B atob(A aobj, B bobj);
}

@Mapper
public interface MyClassMapper<MyAClass, MyBClass> {
}

error: 
error: In type : A and Out type : B differs and this kind of conversion is not supported here
error: In type : B and Out type : A differs and this kind of conversion is not supported here
error: Failed to generate mapping method for type A to B not supported on com.test.IMapper.atob(A,B) !

Can we not reduce the generics first and then generate code?

**Comment by slemesle** [comment]
This should now be fixed for both error cases.

**Comment by anoop44** [comment]
Anyone got this working? I am still getting NullPointer exception on v0.14
